# Generated by Django 4.0.2 on 2022-02-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsrapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Категория новости'),
        ),
    ]
