# Generated by Django 4.0.2 on 2022-02-06 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firsrapp', '0004_alter_news_category_alter_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='firsrapp.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(default='', upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
