# Generated by Django 4.0.2 on 2022-02-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firsrapp', '0005_alter_news_category_alter_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(default=' ', upload_to='photos/%Y/%m/%d'),
        ),
    ]
